### ISSUE TITLE
Design Projects overview page components

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.rsv#25]
## What's the problem you want solved?

We want an overview page, which displays multiple highways on one page. Therefore we need one component which displays one highway. This component should 

Use the **TailwindUI component** [Alternating with optional testimonial](https://tailwindui.com/components/marketing/sections/feature-sections#component-fea10362c98dcf74d601fab911a1aee3) as initial component.

**Important:** Integrate these components only as static components. **Don't** use dynamic maps or content from jsons. This issue is only for designing the components. Also don't change footer, navigation or something other from Layout components.

## Tasks
- [x] Introduce a new component `<RsvSnippet />`
- [ ] Modularize the component into comfortable sub-components into the same component folder
- [ ] Integrate the component into (and replace current content of) `/radschnellwege` page
- [ ] Design the components according to [design draft](https://www.figma.com/file/5HA4jiVx5oqJBjmgbdRipP/220201_RSV_Projekt?node-id=0%3A1)
