### ISSUE TITLE
Integrate MapLibre GL JS

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.rsv#4]
We want different kind of maps. There should be overview map and small info maps. For this we want to integrate [MapLibre GL JS](https://github.com/maplibre/maplibre-gl-js).

## Tasks
- [x] Add `maplibre-gl` dependency
- [x] Figure out how to use it in Gatsby
- [ ] Add MapTiler Base Layer
- [x] Add additional GeoJSON / VectorTile Layer

**Comment by rush42** [comment]
Is taken care of in https://github.com/FixMyBerlin/fixmy.rsv/pull/28
