### ISSUE TITLE
Custom attribution for `DyanmicMap` and `StaticMap`

### ISSUE THREAD

**Issue by rush42** [FixMyBerlin/fixmy.rsv#49]
## The Problem
The static map images are not necessarily shown in their full size and thus the attribution is not always visible.

## Proposed Solution
Implement a custom attribution component for use in dynamic and static maps and disable the internal attribution tags.

## Tasks
- [ ] implement attribution component
- [ ] disable attribution in static map generation
- [ ] disable attribution in dynamic map
